const SOCCER_DURATION=90,SOCCER_GOALS=3;
let soccerBall=null,soccerPlayers=[],soccerScore=[0,0],soccerTime=0,soccerFinished=false,soccerTimeStop=0,soccerMessage='',soccerMessageLife=0;
function soccerTypePower(t){return {bushin:1.35,dragonknight:1.22,monk:1.18,knight:1.12,magicblade:1.12,qigong:1.08,archmage:1.05,runemage:1.05,fox:1.02,ninja:1.0}[t]||.96}
function soccerReset(afterGoal=false){soccerBall={x:500,y:525,vx:0,vy:0,r:54,spin:0,pendingX:0,pendingY:0};const n=selectedTypes.length;soccerPlayers=[];for(let i=0;i<n;i++){soccerPlayers.push({type:selectedTypes[i],team:0,x:230,y:390+i*(270/Math.max(1,n-1)),vx:0,vy:0,r:25,cd:0,soloCd:afterGoal?2:0,stun:0});soccerPlayers.push({type:selectedTypes[i],team:1,x:770,y:390+i*(270/Math.max(1,n-1)),vx:0,vy:0,r:25,cd:0,soloCd:afterGoal?2:0,stun:0})}}
function setupSoccerBattle(){resetCombatInput();heroes=[new Hero(selectedTypes[0],220,525)];heroIndex=0;boss={hp:1,maxHp:1,dead:false,x:500,y:525,r:1};shots.length=particles.length=walls.length=slashes.length=minions.length=lasers.length=0;soccerScore=[0,0];soccerTime=0;soccerFinished=false;soccerTimeStop=0;soccerMessage='神鉄球サッカー　KICK OFF!';soccerMessageLife=1.5;soccerReset()}
function soccerApplyForce(p,power,spread=0){const dx=soccerBall.x-p.x,dy=soccerBall.y-p.y,d=Math.hypot(dx,dy);if(d>190)return;let n=norm(dx,dy);if(spread){const a=Math.atan2(n.y,n.x)+spread;n={x:Math.cos(a),y:Math.sin(a)}}const speed=Math.hypot(soccerBall.vx,soccerBall.vy),dir=speed>.1?norm(soccerBall.vx,soccerBall.vy):n;const dot=n.x*dir.x+n.y*dir.y,px=dir.x*dot*power,py=dir.y*dot*power;const turn=1/(1+speed*.12),qx=(n.x-dir.x*dot)*power*turn,qy=(n.y-dir.y*dot)*power*turn;const fx=px+qx,fy=py+qy;if(soccerTimeStop>0){soccerBall.pendingX+=fx;soccerBall.pendingY+=fy}else{soccerBall.vx+=fx*26;soccerBall.vy+=fy*26}burst(soccerBall.x,soccerBall.y,p.team?'#ff9ca8':'#8ed8ff',10,170)}
function soccerAttack(p,slot){if(p.cd>0||p.stun>0)return;const base=soccerTypePower(p.type),pow=slot==='a'?2.1:slot==='b'?3.0:3.8;p.cd=slot==='a'?.28:slot==='b'?.55:.85;soccerApplyForce(p,pow*base)}
function soccerSolo(p){if(p.soloCd>0)return;if(p.type==='archmage'){soccerTimeStop=5;p.soloCd=20;soccerMessage='TIME STOP!';soccerMessageLife=1.1;return}if(p.type==='bushin'){soccerApplyForce(p,20);p.soloCd=18;soccerMessage='神速飛び蹴り！';soccerMessageLife=1;return}soccerApplyForce(p,7.5*soccerTypePower(p.type));p.soloCd=14}
function soccerMovePlayer(p,dt,mx,my){if(p.stun>0){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.9;p.vy*=.9;return}const n=Math.hypot(mx,my)>1?norm(mx,my):{x:mx,y:my};p.x+=n.x*heroInfo[p.type].speed*.9*dt;p.y+=n.y*heroInfo[p.type].speed*.9*dt;p.x=clamp(p.x,90,910);p.y=clamp(p.y,155,895)}
function updateSoccerGame(dt){if(soccerFinished)return;if(soccerMessageLife>0)soccerMessageLife-=dt;const stopped=soccerTimeStop>0;if(stopped){soccerTimeStop=Math.max(0,soccerTimeStop-dt);if(soccerTimeStop===0){soccerBall.vx+=soccerBall.pendingX*26;soccerBall.vy+=soccerBall.pendingY*26;soccerBall.pendingX=soccerBall.pendingY=0;soccerMessage='TIME RESUME!';soccerMessageLife=.8}}
 const human=soccerPlayers.find(p=>p.team===0);for(const p of soccerPlayers){p.cd=Math.max(0,p.cd-dt);p.soloCd=Math.max(0,p.soloCd-dt);p.stun=Math.max(0,p.stun-dt);if(stopped&&p.type!=='archmage')continue;if(p===human){const mx=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+joy.x,my=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+joy.y;soccerMovePlayer(p,dt,mx,my);if(pressed.has('KeyJ'))soccerAttack(p,'a');if(pressed.has('KeyK'))soccerAttack(p,'b');if(pressed.has('KeyL'))soccerAttack(p,'c');if(pressed.has('KeyI'))soccerSolo(p)}else{const target=soccerBall,side=p.team?1:-1,tx=target.x+side*75,ty=target.y+(p.team?1:-1)*((soccerPlayers.indexOf(p)%3)-1)*55,s=norm(tx-p.x,ty-p.y);soccerMovePlayer(p,dt,s.x,s.y);if(Math.hypot(target.x-p.x,target.y-p.y)<170&&Math.random()<dt*2.4)soccerAttack(p,Math.random()<.65?'a':'b');if((p.type==='archmage'||p.type==='bushin')&&p.soloCd<=0&&Math.hypot(target.x-p.x,target.y-p.y)<190&&Math.random()<dt*.12)soccerSolo(p)}}pressed.clear();released.clear();
 if(!stopped){soccerTime+=dt;soccerBall.x+=soccerBall.vx*dt;soccerBall.y+=soccerBall.vy*dt;soccerBall.vx*=Math.pow(.992,dt*60);soccerBall.vy*=Math.pow(.992,dt*60);soccerBall.spin+=Math.hypot(soccerBall.vx,soccerBall.vy)*dt*.012;const edge=Math.abs(soccerBall.y-525)/370;if(edge>.72)soccerBall.vy+=(525-soccerBall.y)*(.12+edge*.38)*dt;soccerBall.y=clamp(soccerBall.y,145+soccerBall.r,905-soccerBall.r)}
 for(const p of soccerPlayers){const dx=p.x-soccerBall.x,dy=p.y-soccerBall.y,d=Math.hypot(dx,dy),min=p.r+soccerBall.r;if(d<min){const n=norm(dx,dy),over=min-d;p.x+=n.x*over;p.y+=n.y*over;const sp=Math.hypot(soccerBall.vx,soccerBall.vy);if(sp>90){p.vx=n.x*sp*.72;p.vy=n.y*sp*.72;p.stun=Math.min(1.1,.2+sp/520);soccerBall.vx*=.82;soccerBall.vy*=.82}}}
 if(soccerBall.x<-soccerBall.r){soccerScore[1]++;soccerGoal()}else if(soccerBall.x>1000+soccerBall.r){soccerScore[0]++;soccerGoal()}if(soccerTime>=SOCCER_DURATION)finishSoccer();updateUI()}
function soccerGoal(){soccerMessage='GOAL!';soccerMessageLife=1.4;if(Math.max(...soccerScore)>=SOCCER_GOALS){finishSoccer();return}soccerReset(true)}
function finishSoccer(){soccerFinished=true;running=false;const win=soccerScore[0]>soccerScore[1],draw=soccerScore[0]===soccerScore[1];notice(draw?'DRAW':win?'神鉄球サッカー 勝利！':'神鉄球サッカー 敗北…',draw?'#fff':'#ffe77a',2600);setTimeout(()=>ui.start.style.display='grid',1800)}
function drawSoccerGame(){ctx.save();ctx.fillStyle='#171c24';ctx.fillRect(0,100,1000,900);ctx.fillStyle='#26303a';ctx.fillRect(55,135,890,770);ctx.strokeStyle='#d6e1ea';ctx.lineWidth=4;ctx.strokeRect(55,135,890,770);ctx.setLineDash([18,14]);ctx.beginPath();ctx.moveTo(500,135);ctx.lineTo(500,905);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#234d70';ctx.fillRect(0,345,55,360);ctx.fillStyle='#702f3b';ctx.fillRect(945,345,55,360);for(let y=180;y<880;y+=95){const a=Math.abs(y-525)/355;ctx.globalAlpha=.25+.5*a;ctx.fillStyle=y<525?'#ffe07d':'#8fe7ff';ctx.font='bold 28px sans-serif';ctx.textAlign='center';ctx.fillText(y<525?'▼':'▲',500,y)}ctx.globalAlpha=1;for(const p of soccerPlayers){ctx.save();ctx.globalAlpha=p.stun>0?.65:1;const im=sprites['hero_'+p.type];if(!drawSprite(im,p.x,p.y,72,82,p.team===1)){ctx.fillStyle=p.team?'#df6674':'#5ca9e8';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}ctx.strokeStyle=p.team?'#ff9bab':'#a9e5ff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,p.r+4,0,Math.PI*2);ctx.stroke();ctx.restore()}ctx.save();ctx.translate(soccerBall.x,soccerBall.y);ctx.rotate(soccerBall.spin);ctx.fillStyle='#67717a';ctx.strokeStyle='#e5f2ff';ctx.lineWidth=7;ctx.beginPath();ctx.arc(0,0,soccerBall.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle='#a9c1cf';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,30,0,Math.PI*2);ctx.moveTo(-52,0);ctx.lineTo(52,0);ctx.moveTo(0,-52);ctx.lineTo(0,52);ctx.stroke();ctx.fillStyle='#fff';ctx.font='bold 15px sans-serif';ctx.textAlign='center';ctx.fillText('神鉄',0,5);ctx.restore();ctx.fillStyle='#fff';ctx.font='bold 32px sans-serif';ctx.textAlign='center';ctx.fillText(`${soccerScore[0]}  -  ${soccerScore[1]}`,500,105);ctx.font='bold 20px sans-serif';ctx.fillText(`残り ${Math.max(0,SOCCER_DURATION-soccerTime).toFixed(1)}秒　3点先取`,500,132);if(soccerTimeStop>0){ctx.fillStyle='#a8dcff';ctx.font='bold 24px sans-serif';ctx.fillText(`TIME STOP ${soccerTimeStop.toFixed(1)}`,500,168)}if(soccerMessageLife>0){ctx.fillStyle='#fff3a8';ctx.font='bold 42px sans-serif';ctx.fillText(soccerMessage,500,265)}ctx.fillStyle='#dbe9f2';ctx.font='bold 17px sans-serif';ctx.fillText('方向キー：移動　A/B/C：攻撃　D：1人専用スキル（交代なし・HPなし）',500,940);ctx.restore()}
