const SOCCER_DURATION=90,SOCCER_GOALS=3;
let soccerBall=null,soccerPlayers=[],soccerScore=[0,0],soccerTime=0,soccerFinished=false,soccerTimeStop=0,soccerMessage='',soccerMessageLife=0,soccerEffects=[],soccerEnemyTypes=[];
const SOCCER_GOAL_TOP=405,SOCCER_GOAL_BOTTOM=645,SOCCER_CUT=110;
function soccerTypePower(t){return {bushin:1.35,dragonknight:1.22,monk:1.18,knight:1.12,magicblade:1.12,qigong:1.08,archmage:1.05,runemage:1.05,fox:1.02,ninja:1.0}[t]||.96}
function soccerRandomEnemyTypes(n){const pool=Object.keys(heroInfo).filter(t=>!selectedTypes.includes(t));for(let i=pool.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]]}return pool.slice(0,n)}
function soccerReset(afterGoal=false){soccerBall={x:500,y:525,vx:0,vy:0,r:54,spin:0,pendingX:0,pendingY:0};const n=selectedTypes.length;soccerPlayers=[];soccerEffects.length=0;for(let i=0;i<n;i++){const role=n>1&&i===n-1?'jammer':'ball';soccerPlayers.push({type:selectedTypes[i],team:0,role,x:230,y:390+i*(270/Math.max(1,n-1)),vx:0,vy:0,r:25,cd:0,soloCd:afterGoal?2:0,stun:0,aimX:1,aimY:0});soccerPlayers.push({type:soccerEnemyTypes[i]||'knight',team:1,role,x:770,y:390+i*(270/Math.max(1,n-1)),vx:0,vy:0,r:25,cd:0,soloCd:afterGoal?2:0,stun:0,aimX:-1,aimY:0})}}
function setupSoccerBattle(){resetCombatInput();heroes=[new Hero(selectedTypes[0],220,525)];heroIndex=0;boss={hp:1,maxHp:1,dead:false,x:500,y:525,r:1};shots.length=particles.length=walls.length=slashes.length=minions.length=lasers.length=0;soccerScore=[0,0];soccerTime=0;soccerFinished=false;soccerTimeStop=0;soccerMessage='神鉄球サッカー　KICK OFF!';soccerMessageLife=1.5;soccerEnemyTypes=soccerRandomEnemyTypes(selectedTypes.length);soccerReset()}
function soccerApplyForce(p,power,spread=0){const dx=soccerBall.x-p.x,dy=soccerBall.y-p.y,d=Math.hypot(dx,dy);if(d>190)return;let n=norm(dx,dy);if(spread){const a=Math.atan2(n.y,n.x)+spread;n={x:Math.cos(a),y:Math.sin(a)}}const speed=Math.hypot(soccerBall.vx,soccerBall.vy),dir=speed>.1?norm(soccerBall.vx,soccerBall.vy):n;const dot=n.x*dir.x+n.y*dir.y,px=dir.x*dot*power,py=dir.y*dot*power;const turn=1/(1+speed*.12),qx=(n.x-dir.x*dot)*power*turn,qy=(n.y-dir.y*dot)*power*turn;const fx=px+qx,fy=py+qy;if(soccerTimeStop>0){soccerBall.pendingX+=fx;soccerBall.pendingY+=fy}else{soccerBall.vx+=fx*26;soccerBall.vy+=fy*26}burst(soccerBall.x,soccerBall.y,p.team?'#ff9ca8':'#8ed8ff',10,170)}
function soccerAttackEffect(p,slot,power){const dir=norm(p.aimX||((p.team)?-1:1),p.aimY||0),life=slot==='a'?.18:slot==='b'?.26:.34;soccerEffects.push({kind:'strike',x:p.x,y:p.y,dx:dir.x,dy:dir.y,life,max:life,slot,team:p.team,power})}
function soccerHitPlayers(p,power){const dir=norm(p.aimX||((p.team)?-1:1),p.aimY||0);for(const q of soccerPlayers){if(q.team===p.team||q===p)continue;const dx=q.x-p.x,dy=q.y-p.y,d=Math.hypot(dx,dy);if(d>120)continue;const n=norm(dx,dy);if(n.x*dir.x+n.y*dir.y<.25)continue;q.vx+=dir.x*power*42;q.vy+=dir.y*power*42;q.stun=Math.max(q.stun,.12+power*.045);burst(q.x,q.y,p.team?'#ff9ca8':'#8ed8ff',6,120)}}
function soccerRuneAttack(p,slot,power){const dir=norm(p.aimX||((p.team)?-1:1),p.aimY||0),dist=slot==='a'?72:slot==='b'?92:112,radius=slot==='a'?72:slot==='b'?92:112;const rune={team:p.team,x:p.x+dir.x*dist,y:p.y+dir.y*dist,aimX:dir.x,aimY:dir.y};soccerEffects.push({kind:'rune',x:rune.x,y:rune.y,life:.55,max:.55,slot,team:p.team,r:radius});soccerApplyForce(rune,power);for(const q of soccerPlayers){if(q.team===p.team)continue;const dx=q.x-rune.x,dy=q.y-rune.y,d=Math.hypot(dx,dy);if(d<radius){const n=norm(dx,dy);q.vx+=n.x*power*34;q.vy+=n.y*power*34;q.stun=Math.max(q.stun,.12+power*.035)}}burst(rune.x,rune.y,p.team?'#ff8ca8':'#72d8ff',12,150)}
function soccerAttack(p,slot){if(p.cd>0||p.stun>0)return;const base=soccerTypePower(p.type),pow=slot==='a'?2.1:slot==='b'?3.0:3.8;p.cd=slot==='a'?.28:slot==='b'?.55:.85;if(p.type==='runemage'){soccerRuneAttack(p,slot,pow*base);return}soccerAttackEffect(p,slot,pow*base);soccerApplyForce(p,pow*base);soccerHitPlayers(p,pow*base)}
function soccerSolo(p){if(p.soloCd>0)return;if(p.type==='archmage'){soccerTimeStop=5;p.soloCd=20;soccerMessage='TIME STOP!';soccerMessageLife=1.1;return}if(p.type==='bushin'){soccerApplyForce(p,20);p.soloCd=18;soccerMessage='神速飛び蹴り！';soccerMessageLife=1;return}soccerApplyForce(p,7.5*soccerTypePower(p.type));p.soloCd=14}
function soccerReflect(vx,vy,nx,ny){const d=vx*nx+vy*ny;return d<0?{x:vx-2*d*nx,y:vy-2*d*ny}:{x:vx,y:vy}}
function soccerConstrain(o,isBall=false){const r=o.r||0,s=Math.SQRT2;function hit(amount,nx,ny){if(amount<=0)return;o.x+=nx*amount;o.y+=ny*amount;if(isBall){const v=soccerReflect(o.vx,o.vy,nx,ny);o.vx=v.x;o.vy=v.y}}
 hit(145+r-o.y,0,1);hit(o.y-(905-r),0,-1);
 const leftOpen=isBall&&o.y>=SOCCER_GOAL_TOP&&o.y<=SOCCER_GOAL_BOTTOM,rightOpen=leftOpen;
 if(!leftOpen)hit(55+r-o.x,1,0);if(!rightOpen)hit(o.x-(945-r),-1,0);
 hit(310+r*s-(o.x+o.y),1/s,1/s);hit((-690+r*s)-(o.y-o.x),-1/s,1/s);hit((o.y-o.x)-(740-r*s),1/s,-1/s);hit((o.x+o.y)-(1740-r*s),-1/s,-1/s)}
function soccerMovePlayer(p,dt,mx,my){if(p.stun>0){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.9;p.vy*=.9;soccerConstrain(p,false);return}const n=Math.hypot(mx,my)>1?norm(mx,my):{x:mx,y:my};if(Math.hypot(n.x,n.y)>.12){p.aimX=n.x;p.aimY=n.y}p.x+=n.x*heroInfo[p.type].speed*.9*dt;p.y+=n.y*heroInfo[p.type].speed*.9*dt;soccerConstrain(p,false)}
function updateSoccerGame(dt){if(soccerFinished)return;if(soccerMessageLife>0)soccerMessageLife-=dt;const stopped=soccerTimeStop>0;if(stopped){soccerTimeStop=Math.max(0,soccerTimeStop-dt);if(soccerTimeStop===0){soccerBall.vx+=soccerBall.pendingX*26;soccerBall.vy+=soccerBall.pendingY*26;soccerBall.pendingX=soccerBall.pendingY=0;soccerMessage='TIME RESUME!';soccerMessageLife=.8}}
 const human=soccerPlayers.find(p=>p.team===0);for(const p of soccerPlayers){p.cd=Math.max(0,p.cd-dt);p.soloCd=Math.max(0,p.soloCd-dt);p.stun=Math.max(0,p.stun-dt);if(stopped&&p.type!=='archmage')continue;if(p===human){const mx=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+joy.x,my=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+joy.y;soccerMovePlayer(p,dt,mx,my);if(pressed.has('KeyJ'))soccerAttack(p,'a');if(pressed.has('KeyK'))soccerAttack(p,'b');if(pressed.has('KeyL'))soccerAttack(p,'c');if(pressed.has('KeyI'))soccerSolo(p)}else{let target=soccerBall;if(p.role==='jammer'){const foes=soccerPlayers.filter(q=>q.team!==p.team);target=foes.reduce((best,q)=>Math.hypot(q.x-soccerBall.x,q.y-soccerBall.y)<Math.hypot(best.x-soccerBall.x,best.y-soccerBall.y)?q:best,foes[0]);const side=p.team?1:-1,tx=target.x+side*48,ty=target.y,s=norm(tx-p.x,ty-p.y);soccerMovePlayer(p,dt,s.x,s.y);p.aimX=target.x-p.x;p.aimY=target.y-p.y;if(Math.hypot(target.x-p.x,target.y-p.y)<125&&Math.random()<dt*3.2)soccerAttack(p,Math.random()<.72?'a':'b')}else{const side=p.team?1:-1,tx=target.x+side*75,ty=target.y+(p.team?1:-1)*((soccerPlayers.indexOf(p)%3)-1)*55,s=norm(tx-p.x,ty-p.y);soccerMovePlayer(p,dt,s.x,s.y);p.aimX=target.x-p.x;p.aimY=target.y-p.y;if(Math.hypot(target.x-p.x,target.y-p.y)<170&&Math.random()<dt*2.4)soccerAttack(p,Math.random()<.65?'a':'b');if((p.type==='archmage'||p.type==='bushin')&&p.soloCd<=0&&Math.hypot(target.x-p.x,target.y-p.y)<190&&Math.random()<dt*.12)soccerSolo(p)}}}pressed.clear();released.clear();
 for(let i=soccerEffects.length-1;i>=0;i--){soccerEffects[i].life-=dt;if(soccerEffects[i].life<=0)soccerEffects.splice(i,1)}
 if(!stopped){soccerTime+=dt;soccerBall.x+=soccerBall.vx*dt;soccerBall.y+=soccerBall.vy*dt;soccerBall.vx*=Math.pow(.992,dt*60);soccerBall.vy*=Math.pow(.992,dt*60);soccerBall.spin+=Math.hypot(soccerBall.vx,soccerBall.vy)*dt*.012;const edge=Math.abs(soccerBall.y-525)/370;if(edge>.72)soccerBall.vy+=(525-soccerBall.y)*(.12+edge*.38)*dt;soccerConstrain(soccerBall,true)}
 for(const p of soccerPlayers){const dx=p.x-soccerBall.x,dy=p.y-soccerBall.y,d=Math.hypot(dx,dy),min=p.r+soccerBall.r;if(d<min){const n=norm(dx,dy),over=min-d;p.x+=n.x*over;p.y+=n.y*over;const sp=Math.hypot(soccerBall.vx,soccerBall.vy);if(sp>90){p.vx=n.x*sp*.72;p.vy=n.y*sp*.72;p.stun=Math.min(1.1,.2+sp/520);soccerBall.vx*=.82;soccerBall.vy*=.82}}soccerConstrain(p,false)}
 const inGoal=soccerBall.y>=SOCCER_GOAL_TOP&&soccerBall.y<=SOCCER_GOAL_BOTTOM;if(inGoal&&soccerBall.x<-soccerBall.r){soccerScore[1]++;soccerGoal()}else if(inGoal&&soccerBall.x>1000+soccerBall.r){soccerScore[0]++;soccerGoal()}if(soccerTime>=SOCCER_DURATION)finishSoccer();updateUI()}
function soccerGoal(){soccerMessage='GOAL!';soccerMessageLife=1.4;if(Math.max(...soccerScore)>=SOCCER_GOALS){finishSoccer();return}soccerReset(true)}
function finishSoccer(){soccerFinished=true;running=false;const win=soccerScore[0]>soccerScore[1],draw=soccerScore[0]===soccerScore[1];notice(draw?'DRAW':win?'神鉄球サッカー 勝利！':'神鉄球サッカー 敗北…',draw?'#fff':'#ffe77a',2600);setTimeout(()=>ui.start.style.display='grid',1800)}
function soccerFieldPath(){ctx.beginPath();ctx.moveTo(165,145);ctx.lineTo(835,145);ctx.lineTo(945,255);ctx.lineTo(945,795);ctx.lineTo(835,905);ctx.lineTo(165,905);ctx.lineTo(55,795);ctx.lineTo(55,255);ctx.closePath()}
function drawSoccerGame(){ctx.save();ctx.fillStyle='#171c24';ctx.fillRect(0,100,1000,900);soccerFieldPath();ctx.fillStyle='#26303a';ctx.fill();ctx.strokeStyle='#d6e1ea';ctx.lineWidth=4;ctx.stroke();ctx.setLineDash([18,14]);ctx.beginPath();ctx.moveTo(500,145);ctx.lineTo(500,905);ctx.stroke();ctx.setLineDash([]);
 ctx.fillStyle='#234d70';ctx.fillRect(0,SOCCER_GOAL_TOP,55,SOCCER_GOAL_BOTTOM-SOCCER_GOAL_TOP);ctx.fillStyle='#702f3b';ctx.fillRect(945,SOCCER_GOAL_TOP,55,SOCCER_GOAL_BOTTOM-SOCCER_GOAL_TOP);ctx.strokeStyle='#d6e1ea';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(55,255);ctx.lineTo(55,SOCCER_GOAL_TOP);ctx.moveTo(55,SOCCER_GOAL_BOTTOM);ctx.lineTo(55,795);ctx.moveTo(945,255);ctx.lineTo(945,SOCCER_GOAL_TOP);ctx.moveTo(945,SOCCER_GOAL_BOTTOM);ctx.lineTo(945,795);ctx.stroke();
 for(const y of [185,255,330,405,645,720,795,870]){const dist=Math.abs(y-525)/390,size=14+dist*28,arrow=y<525?'▼':'▲';ctx.globalAlpha=.18+dist*.5;ctx.fillStyle=y<525?'#ffe07d':'#8fe7ff';ctx.font=`bold ${size}px sans-serif`;ctx.textAlign='center';for(let x=120;x<=880;x+=95)ctx.fillText(arrow,x,y)}ctx.globalAlpha=1;
 for(const e of soccerEffects){const t=e.life/e.max;ctx.save();ctx.globalAlpha=Math.max(0,t);if(e.kind==='rune'){ctx.translate(e.x,e.y);ctx.strokeStyle=e.team?'#ff91ad':'#74dfff';ctx.lineWidth=5;ctx.shadowBlur=18;ctx.shadowColor=ctx.strokeStyle;ctx.beginPath();ctx.arc(0,0,e.r*(1.08-t*.08),0,Math.PI*2);ctx.stroke();ctx.rotate((1-t)*1.8);ctx.beginPath();for(let i=0;i<6;i++){const a=i*Math.PI/3;const x=Math.cos(a)*e.r*.72,y=Math.sin(a)*e.r*.72;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.stroke()}else{const len=(e.slot==='a'?60:e.slot==='b'?85:112)*(1-t*.25),w=e.slot==='a'?8:e.slot==='b'?13:18;ctx.translate(e.x,e.y);ctx.rotate(Math.atan2(e.dy,e.dx));ctx.strokeStyle=e.team?'#ff9cab':'#9ee8ff';ctx.lineWidth=w*t+2;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(18,0);ctx.lineTo(len,0);ctx.stroke();ctx.strokeStyle='#fff7c8';ctx.lineWidth=Math.max(2,w*.32);ctx.beginPath();ctx.moveTo(24,0);ctx.lineTo(len*.82,0);ctx.stroke()}ctx.restore()}
 for(const p of soccerPlayers){ctx.save();ctx.globalAlpha=p.stun>0?.65:1;const im=p.type==='bushin'?(sprites.boss_bushin||sprites.hero_bushin):sprites['hero_'+p.type];const sw=p.type==='bushin'?80:72,sh=p.type==='bushin'?90:82;if(!drawSprite(im,p.x,p.y,sw,sh,p.team===1)){ctx.fillStyle=p.team?'#df6674':'#5ca9e8';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}ctx.strokeStyle=p.team?'#ff6f86':'#62bfff';ctx.lineWidth=p.role==='jammer'?6:3;ctx.beginPath();ctx.arc(p.x,p.y,p.r+4,0,Math.PI*2);ctx.stroke();ctx.restore()}
 ctx.save();ctx.translate(soccerBall.x,soccerBall.y);ctx.rotate(soccerBall.spin);ctx.fillStyle='#67717a';ctx.strokeStyle='#e5f2ff';ctx.lineWidth=7;ctx.beginPath();ctx.arc(0,0,soccerBall.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle='#a9c1cf';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,30,0,Math.PI*2);ctx.moveTo(-52,0);ctx.lineTo(52,0);ctx.moveTo(0,-52);ctx.lineTo(0,52);ctx.stroke();ctx.fillStyle='#fff';ctx.font='bold 15px sans-serif';ctx.textAlign='center';ctx.fillText('神鉄',0,5);ctx.restore();ctx.fillStyle='#fff';ctx.font='bold 32px sans-serif';ctx.textAlign='center';ctx.fillText(`${soccerScore[0]}  -  ${soccerScore[1]}`,500,105);ctx.font='bold 20px sans-serif';ctx.fillText(`残り ${Math.max(0,SOCCER_DURATION-soccerTime).toFixed(1)}秒　3点先取`,500,132);if(soccerTimeStop>0){ctx.fillStyle='#a8dcff';ctx.font='bold 24px sans-serif';ctx.fillText(`TIME STOP ${soccerTimeStop.toFixed(1)}`,500,168)}if(soccerMessageLife>0){ctx.fillStyle='#fff3a8';ctx.font='bold 42px sans-serif';ctx.fillText(soccerMessage,500,265)}ctx.fillStyle='#dbe9f2';ctx.font='bold 17px sans-serif';ctx.fillText('方向キー：移動　A/B/C：攻撃　D：1人専用スキル（太いチーム色の枠は妨害役）',500,940);ctx.restore()}
